/**
 * quiz-generator — Combines persistent state + LLM subagent reasoning.
 *
 * Demonstrates the ultimate Gallery-impossible pattern:
 * 1. Reads from persistent knowledge base (cross-skill state sharing)
 * 2. Calls Gemma 4 to generate contextual quiz questions
 * 3. Tracks quiz history for spaced-repetition-style learning
 *
 * This skill is a TRUE SUBAGENT: it has memory, reasons, and adapts.
 */

const KB_KEY = 'knowledge_tracker_db';
const QUIZ_KEY = 'quiz_history';

function loadKB() {
  const raw = localStorage.getItem(KB_KEY);
  return raw ? JSON.parse(raw) : { topics: {} };
}

function loadQuizHistory() {
  const raw = localStorage.getItem(QUIZ_KEY);
  return raw ? JSON.parse(raw) : { quizzes: [], total_questions: 0 };
}

function saveQuizHistory(history) {
  localStorage.setItem(QUIZ_KEY, JSON.stringify(history));
}

window['ai_edge_gallery_get_result'] = async (dataStr) => {
  try {
    const input = JSON.parse(dataStr);
    const topic = (input.topic || '').toLowerCase().trim();
    const count = parseInt(input.count) || 3;
    const style = input.style || 'multiple_choice';

    if (!topic) {
      return JSON.stringify({ error: 'No topic provided. Specify a topic you have researched.' });
    }

    // Load knowledge base (shared with knowledge-tracker skill)
    const kb = loadKB();
    const topicData = kb.topics[topic];

    if (!topicData) {
      const available = Object.keys(kb.topics);
      if (available.length === 0) {
        return JSON.stringify({
          error: 'Knowledge base is empty. Research some topics first using the learn pipeline.'
        });
      }
      return JSON.stringify({
        error: `No knowledge on "${topic}". Available topics: ${available.join(', ')}`
      });
    }

    // Check if LLM is available
    if (!__skillos || !__skillos.llm || !__skillos.llm.available) {
      // Fallback: generate simple fact-recall questions without LLM
      const questions = (topicData.key_facts || []).slice(0, count).map((fact, i) => ({
        question: `True or False: ${fact}`,
        answer: 'True',
        type: 'true_false',
      }));
      return JSON.stringify({
        result: formatQuiz(topic, questions, 'heuristic')
      });
    }

    // Build context from stored knowledge
    const context = [
      `Topic: ${topic}`,
      `Summary: ${topicData.summary || 'N/A'}`,
      `Key Facts:\n${(topicData.key_facts || []).map(f => `- ${f}`).join('\n')}`,
    ];
    if (topicData.surprises && topicData.surprises.length > 0) {
      context.push(`Surprising insights:\n${topicData.surprises.map(s => `- ${s}`).join('\n')}`);
    }

    // Use Gemma 4 to generate quiz questions
    const stylePrompt = {
      multiple_choice: 'Each question should have 4 options (A, B, C, D) with one correct answer.',
      true_false: 'Each question should be a True/False statement.',
      open: 'Each question should be open-ended, requiring a short written answer.',
    }[style] || '';

    const prompt = `Generate exactly ${count} quiz questions about "${topic}" to test comprehension.

${stylePrompt}

Base the questions ONLY on these facts (do not invent information):
${context.join('\n')}

Respond with valid JSON only:
{
  "questions": [
    {
      "question": "the question text",
      "options": ["A) ...", "B) ...", "C) ...", "D) ..."],
      "answer": "the correct answer",
      "explanation": "brief explanation why"
    }
  ]
}`;

    const quizData = await __skillos.llm.chatJSON(prompt, null, {
      temperature: 0.5,
      max_tokens: 1500,
    });

    const questions = quizData.questions || [];

    // Track quiz history
    const history = loadQuizHistory();
    history.quizzes.push({
      topic,
      count: questions.length,
      style,
      timestamp: new Date().toISOString(),
    });
    history.total_questions += questions.length;
    saveQuizHistory(history);

    return JSON.stringify({
      result: formatQuiz(topic, questions, 'gemma4-subagent')
    });

  } catch (e) {
    return JSON.stringify({ error: `Quiz generation failed: ${e.message}` });
  }
};

function formatQuiz(topic, questions, method) {
  let output = `## Quiz: ${topic}\n`;
  output += `*Generated by ${method} | ${questions.length} questions*\n\n`;

  questions.forEach((q, i) => {
    output += `**Q${i + 1}.** ${q.question}\n`;
    if (q.options && q.options.length > 0) {
      q.options.forEach(opt => { output += `  ${opt}\n`; });
    }
    output += `\n`;
  });

  output += `---\n**Answers:**\n`;
  questions.forEach((q, i) => {
    output += `Q${i + 1}: ${q.answer}`;
    if (q.explanation) output += ` — ${q.explanation}`;
    output += `\n`;
  });

  return output;
}
